mode = "dark"
accent = "#61AFEF"
selection = "#3E4451"
muted = "#5C6370"
background = "#282C34"
dark_background = "#21252B"
darker_background = "#1B1D23"
lighter_background = "#2C313C"
foreground = "#ABB2BF"
dark_foreground = "#5C6370"
light_foreground = "#D7DAE0"
bright_foreground = "#FFFFFF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
cyan = "#56B6C2"
blue = "#61AFEF"
magenta = "#C678DD"
brown = "#D19A66"
bright_red = "#E06C75"
bright_yellow = "#E5C07B"
bright_green = "#98C379"
bright_cyan = "#56B6C2"
bright_blue = "#61AFEF"
bright_magenta = "#C678DD"