mode = "dark"
accent = "#7AA2F7"
selection = "#292E42"
muted = "#565F89"
background = "#1F2335"
dark_background = "#191A2A"
darker_background = "#16161E"
lighter_background = "#292E42"
foreground = "#C0CAF5"
dark_foreground = "#565F89"
light_foreground = "#A9B1D6"
bright_foreground = "#C0CAF5"
red = "#F7768E"
yellow = "#E0AF68"
orange = "#FF9E64"
green = "#9ECE6A"
cyan = "#7DCFFF"
blue = "#7AA2F7"
magenta = "#BB9AF7"
brown = "#FF9E64"
bright_red = "#F7768E"
bright_yellow = "#E0AF68"
bright_green = "#9ECE6A"
bright_cyan = "#7DCFFF"
bright_blue = "#7AA2F7"
bright_magenta = "#BB9AF7"