mode = "dark"
accent = "#7E9CD8"
selection = "#363646"
muted = "#727169"
background = "#1F1F28"
dark_background = "#181820"
darker_background = "#16161D"
lighter_background = "#2A2A37"
foreground = "#DCD7BA"
dark_foreground = "#727169"
light_foreground = "#C8C093"
bright_foreground = "#DCD7BA"
red = "#C34043"
yellow = "#DCA561"
orange = "#FFA066"
green = "#76946A"
cyan = "#6A9589"
blue = "#7E9CD8"
magenta = "#957FB8"
brown = "#8A6651"
bright_red = "#E82424"
bright_yellow = "#E6C384"
bright_green = "#98BB6C"
bright_cyan = "#7AA89F"
bright_blue = "#7FB4CA"
bright_magenta = "#938AA9"
