mode = "dark"
accent = "#ffd173"
selection = "#3e4b59"
muted = "#707a8c"
background = "#1f2430"
dark_background = "#191e2a"
darker_background = "#151a24"
lighter_background = "#242936"
foreground = "#cbccc6"
dark_foreground = "#707a8c"
light_foreground = "#b8c0cc"
bright_foreground = "#f0f1ec"
red = "#f28779"
yellow = "#ffd580"
orange = "#ffad66"
green = "#bae67e"
cyan = "#95e6cb"
blue = "#73d0ff"
magenta = "#d4bfff"
brown = "#c7a27c"
bright_red = "#f29e8e"
bright_yellow = "#ffd580"
bright_green = "#bae67e"
bright_cyan = "#95e6cb"
bright_blue = "#73d0ff"
bright_magenta = "#d4bfff"
