"$schema" = 'https://starship.rs/config-schema.json'

palette = "matugen"

format = """
$directory\
$git_branch\
$git_status
$character
"""

[palettes.matugen]
foreground = "#f0dee0"
primary = "#ffb2bf"
secondary = "#d9a8b0"
tertiary = "#e6a8b8"
error = "#ffb4ab"
muted = "#cbbfc1"

[directory]
style = "bold fg:secondary"
truncation_length = 3
truncate_to_repo = false
format = "[$path](fg:secondary) "

[git_branch]
symbol = "󰘬 "
style = "bold fg:tertiary"
format = "[$symbol$branch](fg:tertiary) "

[git_status]
style = "fg:primary"
format = "[$all_status$ahead_behind](fg:primary) "

[character]
success_symbol = "[❯](bold fg:primary)"
error_symbol = "[❯](bold fg:error)"
vimcmd_symbol = "[❮](bold fg:primary)"

[cmd_duration]
min_time = 2000
format = " took [$duration](fg:muted)"
