mode = "dark"
accent = "#268BD2"
selection = "#073642"
muted = "#586E75"
background = "#002B36"
dark_background = "#00212B"
darker_background = "#001F27"
lighter_background = "#073642"
foreground = "#839496"
dark_foreground = "#586E75"
light_foreground = "#93A1A1"
bright_foreground = "#EEE8D5"
red = "#DC322F"
yellow = "#B58900"
orange = "#CB4B16"
green = "#859900"
cyan = "#2AA198"
blue = "#268BD2"
magenta = "#D33682"
brown = "#CB4B16"
bright_red = "#DC322F"
bright_yellow = "#B58900"
bright_green = "#859900"
bright_cyan = "#2AA198"
bright_blue = "#268BD2"
bright_magenta = "#D33682"