mode = "dark"
accent = "#88C0D0"
selection = "#434C5E"
muted = "#616E88"
background = "#2E3440"
dark_background = "#242933"
darker_background = "#1E222A"
lighter_background = "#3B4252"
foreground = "#D8DEE9"
dark_foreground = "#616E88"
light_foreground = "#E5E9F0"
bright_foreground = "#ECEFF4"
red = "#BF616A"
yellow = "#EBCB8B"
orange = "#D08770"
green = "#A3BE8C"
cyan = "#8FBCBB"
blue = "#5E81AC"
magenta = "#B48EAD"
brown = "#D08770"
bright_red = "#BF616A"
bright_yellow = "#EBCB8B"
bright_green = "#A3BE8C"
bright_cyan = "#8FBCBB"
bright_blue = "#81A1C1"
bright_magenta = "#B48EAD"