mode = "dark"
accent = "#888888"
selection = "#222222"
muted = "#999999"
background = "#000000"
dark_background = "#121212"
darker_background = "#000000"
lighter_background = "#222222"
foreground = "#c1c1c1"
dark_foreground = "#999999"
light_foreground = "#c1c1c1"
bright_foreground = "#c1c1c1"
red = "#5f8787"
yellow = "#a06666"
orange = "#aaaaaa"
green = "#dd9999"
cyan = "#aaaaaa"
blue = "#888888"
magenta = "#999999"
brown = "#444444"
bright_red = "#aaaaaa"
bright_yellow = "#222222"
bright_green = "#dd9999"
bright_cyan = "#aaaaaa"
bright_blue = "#999999"
bright_magenta = "#999999"
