mode = "dark"
accent = "#FF8700"
selection = "#45433E"
muted = "#917E6B"
background = "#121110"
dark_background = "#1C1B19"
darker_background = "#0D0C0B"
lighter_background = "#262522"
foreground = "#C5B088"
dark_foreground = "#917E6B"
light_foreground = "#E2D2B5"
bright_foreground = "#FCE8C3"
red = "#EF2F27"
yellow = "#FBB829"
orange = "#FF5F00"
green = "#519F50"
cyan = "#0AAEB3"
blue = "#2C78BF"
magenta = "#E02C6D"
brown = "#683b15"
bright_red = "#F75341"
bright_yellow = "#FED06E"
bright_green = "#98BC37"
bright_cyan = "#2BE4D0"
bright_blue = "#68A8E4"
bright_magenta = "#FF5C8F"
