mode = "dark"
accent = "#c4a7e7"
selection = "#403d52"
muted = "#6e6a86"
background = "#191724"
dark_background = "#1f1d2e"
darker_background = "#16141f"
lighter_background = "#26233a"
foreground = "#e0def4"
dark_foreground = "#6e6a86"
light_foreground = "#908caa"
bright_foreground = "#e0def4"
red = "#eb6f92"
yellow = "#f6c177"
orange = "#ebbcba"
green = "#95b1ac"
cyan = "#9ccfd8"
blue = "#31748f"
magenta = "#c4a7e7"
brown = "#403d52"
bright_red = "#eb6f92"
bright_yellow = "#f6c177"
bright_green = "#95b1ac"
bright_cyan = "#9ccfd8"
bright_blue = "#31748f"
bright_magenta = "#c4a7e7"
