mode = "dark"

accent = "#ebbcba"
selection = "#403d52"
muted = "#6e6a86"

background = "#191724"
dark_background = "#16141f"
darker_background = "#16141f"
lighter_background = "#26233a"

foreground = "#e0def4"
dark_foreground = "#6e6a86"
light_foreground = "#908caa"
bright_foreground = "#e0def4"

red = "#eb6f92"
yellow = "#f6c177"
orange = "#f09892"
green = "#31748f"
cyan = "#9ccfd8"
blue = "#9ccfd8"
magenta = "#c4a7e7"
brown = "#403d52"

bright_red = "#eb6f92"
bright_yellow = "#f6c177"
bright_green = "#3e8fb0"
bright_cyan = "#9ccfd8"
bright_blue = "#9ccfd8"
bright_magenta = "#c4a7e7"
