mode = "dark"

accent = "#b59790"
selection = "#584e51"
muted = "#584e51"

background = "#0c0b0c"
dark_background = "#090809"
darker_background = "#060606"
lighter_background = "#0c0b0c"

foreground = "#e2dddc"
dark_foreground = "#584e51"
light_foreground = "#cfd3cd"
bright_foreground = "#fafcfb"

red = "#c38b7b"
yellow = "#6b5e73"
orange = "#b59790"
green = "#87a9b0"
cyan = "#a5a0b6"
blue = "#b59790"
magenta = "#c4d8e2"
brown = "#584e51"

bright_red = "#c38b7b"
bright_yellow = "#6b5e73"
bright_green = "#87a9b0"
bright_cyan = "#a5a0b6"
bright_blue = "#b59790"
bright_magenta = "#c4d8e2"
