shell /bin/zsh

font_family JetBrains Mono Nerd Font
font_size 11.5

background_opacity 0.94

cursor_shape beam
cursor_blink_interval 0

enable_audio_bell no
confirm_os_window_close 0
scrollback_lines 10000

include ~/.config/matugen/generated/kitty-colors.conf
